language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 2.1.3
branches:
 - only:
   - master

before_script:
 - dotnet restore

script:
 - dotnet build src/Sample.Api/
 - dotnet test tests/Sample.Tests.EndToEnd/
